GEM_PROFILES = [
    {
        "id": "leonard-diana",
        "name": "Leonard Diana",
        "initials": "LD",
        "display_title": "CEO / Founder",
        "professional_title": "Chief Executive Officer & Founder",
        "company": "GEM Cybersecurity-Monitoring Assist + ATR",
        "division": "Executive Leadership",
        "role_category": "Executive Leadership",
        "profile_type": "executive",
        "credentials": [],
        "years_experience": None,
        "specialization": ["Strategic Leadership", "Cybersecurity", "Business Development", "Trust Services"],
        "verification_status": "Verified Executive",
        "license_status": "Review Active",
        "bio_status": "Active",
        "ceo_approval": "Approved",
        "public_bio": "CEO and Founder of GEM Cybersecurity-Monitoring Assist and Alliance Trust Realty. Leading enterprise security operations, asset protection, and real estate trust services with a commitment to client-first integrity and compliance excellence.",
        "card_badge": "CEO / Founder",
        "contact_email": None,
        "photo_url": None,
        "visibility": "public",
        "risk_level": "medium",
        "next_action": "Attach business authority records and profile evidence",
        "sort_order": 1,
        "accent": "cyan",
        "views": ["executive_board", "vip_visibility", "leadership"],
    },
    {
        "id": "gregor-stewart",
        "name": "Gregor Stewart",
        "initials": "GS",
        "display_title": "Owner / Principal Consultant",
        "professional_title": "Owner · Principal Consultant · Broker & Managing Partner",
        "company": "GEM + Alliance Trust Realty",
        "division": "Real Estate / Security Governance",
        "role_category": "Executive / Realty / Security Governance",
        "profile_type": "executive",
        "credentials": ["CISM"],
        "years_experience": None,
        "specialization": ["Realty Governance", "Security Consulting", "Asset Management", "Compliance"],
        "verification_status": "In Review",
        "license_status": "Evidence Required",
        "bio_status": "Active",
        "ceo_approval": "Pending",
        "public_bio": "Principal Consultant and Managing Partner bridging cybersecurity governance with real estate asset management across GEM and Alliance Trust Realty. Holds CISM certification with expertise in security-informed property investment and trust compliance.",
        "card_badge": "Principal Consultant · CISM · Realty Governance",
        "contact_email": None,
        "photo_url": None,
        "visibility": "public",
        "risk_level": "high",
        "next_action": "Attach CISM proof and realty license evidence",
        "sort_order": 2,
        "accent": "blue",
        "views": ["executive_board", "leadership", "partners"],
    },
    {
        "id": "sarah-johnson",
        "name": "Sarah Johnson",
        "initials": "SJ",
        "display_title": "Chief Information Security Officer",
        "professional_title": "Chief Information Security Officer",
        "company": "Global Financial Partners",
        "division": "Cybersecurity",
        "role_category": "Cybersecurity Leadership",
        "profile_type": "cybersecurity",
        "credentials": ["CISSP", "CISM"],
        "years_experience": 15,
        "specialization": ["Cybersecurity", "Financial Services", "Enterprise Threat Defense"],
        "verification_status": "Verified Bio",
        "license_status": "Credential Evidence Required",
        "bio_status": "Verified",
        "ceo_approval": "Pending GEM + ATR Assignment Approval",
        "public_bio": "Chief Information Security Officer with 15 years of experience in cybersecurity and financial services. CISSP and CISM certified specialist in enterprise threat defense architectures, regulatory compliance, and security program leadership.",
        "card_badge": "CISO · CISSP · CISM",
        "contact_email": None,
        "photo_url": None,
        "visibility": "public",
        "risk_level": "medium",
        "next_action": "Confirm GEM + ATR assignment role and credential proof",
        "sort_order": 3,
        "accent": "cyan",
        "views": ["executive_board", "cybersecurity_team", "leadership"],
    },
    {
        "id": "michael-chen",
        "name": "Michael Chen",
        "initials": "MC",
        "display_title": "Security Compliance Manager",
        "professional_title": "Security Compliance Manager",
        "company": "Secure Banking Solutions",
        "division": "Cybersecurity",
        "role_category": "Compliance / Risk Management",
        "profile_type": "compliance",
        "credentials": ["CISSP", "CFA"],
        "years_experience": 8,
        "specialization": ["Cybersecurity", "Financial Services", "Risk Management", "Compliance"],
        "verification_status": "Verified Bio",
        "license_status": "Credential Evidence Required",
        "bio_status": "Verified",
        "ceo_approval": "Pending GEM + ATR Assignment Approval",
        "public_bio": "Security Compliance Manager with 8 years bridging cybersecurity and financial risk. CISSP and CFA certified with deep expertise in regulatory frameworks, risk quantification, and compliance program design for financial institutions.",
        "card_badge": "Compliance Manager · CISSP · CFA",
        "contact_email": None,
        "photo_url": None,
        "visibility": "public",
        "risk_level": "medium",
        "next_action": "Confirm GEM + ATR assignment role and credential proof",
        "sort_order": 4,
        "accent": "blue",
        "views": ["cybersecurity_team", "leadership"],
    },
    {
        "id": "aisha-patel",
        "name": "Aisha Patel",
        "initials": "AP",
        "display_title": "Threat Intelligence Analyst",
        "professional_title": "Threat Intelligence Analyst",
        "company": "FinSecure Technologies",
        "division": "Cybersecurity",
        "role_category": "Threat Intelligence",
        "profile_type": "cybersecurity",
        "credentials": ["CISSP", "CISM"],
        "years_experience": 6,
        "specialization": ["Cybersecurity", "Financial Services", "Data Analytics", "Threat Intelligence"],
        "verification_status": "Verified Bio",
        "license_status": "Credential Evidence Required",
        "bio_status": "Verified",
        "ceo_approval": "Pending GEM + ATR Assignment Approval",
        "public_bio": "Threat Intelligence Analyst with 6 years specializing in financial sector cyber threats. CISSP and CISM certified with expertise in adversarial threat modeling, dark web monitoring, and AI-driven anomaly detection for enterprise clients.",
        "card_badge": "Threat Intelligence · CISSP · CISM",
        "contact_email": None,
        "photo_url": None,
        "visibility": "public",
        "risk_level": "medium",
        "next_action": "Confirm GEM + ATR assignment role and credential proof",
        "sort_order": 5,
        "accent": "purple",
        "views": ["cybersecurity_team"],
    },
    {
        "id": "ck",
        "name": "Ck",
        "initials": "CK",
        "display_title": "Sales Manager / Agent",
        "professional_title": "Sales Manager & Agent",
        "company": "GEM + ATR",
        "division": "Agent Network",
        "role_category": "Sales / Operations",
        "profile_type": "agent",
        "credentials": [],
        "years_experience": None,
        "specialization": ["Sales Operations", "Client Relations", "Business Development"],
        "verification_status": "Modified Profile",
        "license_status": "Pending Review",
        "bio_status": "In Progress",
        "ceo_approval": "Pending",
        "public_bio": "Sales Manager and Agent operating within the GEM + ATR ecosystem. Focused on client acquisition, service coordination, and sales pipeline management across cybersecurity and real estate verticals.",
        "card_badge": "Sales Agent · GEM + ATR",
        "contact_email": None,
        "photo_url": None,
        "visibility": "public",
        "risk_level": "high",
        "next_action": "Confirm legal name, upload headshot, confirm role scope and license requirement",
        "sort_order": 6,
        "accent": "green",
        "views": ["agent_network"],
    },
    {
        "id": "financial-team-supports",
        "name": "Financial Team Supports",
        "initials": "FT",
        "display_title": "Affiliate Financial Support",
        "professional_title": "Affiliate Financial Support Function",
        "company": "GEM + ATR",
        "division": "Financial Operations",
        "role_category": "Finance / Operations",
        "profile_type": "finance",
        "credentials": [],
        "years_experience": None,
        "specialization": ["Affiliate Finance", "Support Operations", "Financial Oversight"],
        "verification_status": "Verified Function",
        "license_status": "Evidence Required",
        "bio_status": "Active",
        "ceo_approval": "Pending",
        "public_bio": "Affiliated financial support function managing financial oversight, affiliate coordination, and support operations within the GEM + ATR service ecosystem.",
        "card_badge": "Finance Support · Verified Function",
        "contact_email": None,
        "photo_url": None,
        "visibility": "public",
        "risk_level": "high",
        "next_action": "Attach affiliate proof, define service scope and financial-support boundaries",
        "sort_order": 7,
        "accent": "yellow",
        "views": ["agent_network", "vip_visibility"],
    },
    {
        "id": "support-operations-desk",
        "name": "Support Operations Desk",
        "initials": "SO",
        "display_title": "Client Support & Escalation",
        "professional_title": "Client Support & Escalation Desk",
        "company": "GEM + ATR",
        "division": "Support Operations",
        "role_category": "Support / Escalation",
        "profile_type": "support",
        "credentials": [],
        "years_experience": None,
        "specialization": ["Client Support", "Escalation Management", "Service Routing"],
        "verification_status": "Verified Function",
        "license_status": "Not Required",
        "bio_status": "Active",
        "ceo_approval": "Approved",
        "public_bio": "Central client support and escalation function for GEM + ATR. Manages client intake, routing, escalation workflows, and resolution coordination across all service lines.",
        "card_badge": "Support Desk · CEO Approved",
        "contact_email": None,
        "photo_url": None,
        "visibility": "public",
        "risk_level": "low",
        "next_action": "Attach SOP, add escalation matrix and support-routing rules",
        "sort_order": 8,
        "accent": "green",
        "views": ["agent_network", "vip_visibility"],
    },
    {
        "id": "vip-board-desk",
        "name": "VIP Board Desk",
        "initials": "VB",
        "display_title": "VIP Client Relationship Management",
        "professional_title": "VIP Client Relationship Management",
        "company": "GEM + ATR",
        "division": "VIP Services",
        "role_category": "VIP / Executive Relations",
        "profile_type": "vip",
        "credentials": [],
        "years_experience": None,
        "specialization": ["VIP Relations", "Executive Concierge", "Restricted Access Management"],
        "verification_status": "Verified Function",
        "license_status": "Conditional",
        "bio_status": "Active",
        "ceo_approval": "Approved",
        "public_bio": "Restricted VIP client relationship management desk serving executive-tier stakeholders and board-level clients. Managed directly under CEO office oversight.",
        "card_badge": "VIP Desk · Restricted · CEO Approved",
        "contact_email": None,
        "photo_url": None,
        "visibility": "restricted",
        "risk_level": "medium",
        "next_action": "Define restricted access policy, assign internal owners, add VIP handling workflow",
        "sort_order": 9,
        "accent": "gold",
        "views": ["vip_visibility"],
    },
    {
        "id": "ai-agent-overseer",
        "name": "AI Agent Overseer",
        "initials": "AI",
        "display_title": "Automation Governance Agent",
        "professional_title": "Automation Governance Agent",
        "company": "GEM Platform",
        "division": "Platform Automation",
        "role_category": "AI / Automation Governance",
        "profile_type": "ai_agent",
        "credentials": [],
        "years_experience": None,
        "specialization": ["Automation Governance", "AI Oversight", "Workflow Management"],
        "verification_status": "Pending Approval",
        "license_status": "Not Required",
        "bio_status": "Draft",
        "ceo_approval": "Pending",
        "public_bio": "AI-driven automation governance agent overseeing platform workflows, audit trails, and automated service delivery for the GEM platform ecosystem.",
        "card_badge": "AI Agent · Automation · Draft",
        "contact_email": None,
        "photo_url": None,
        "visibility": "internal",
        "risk_level": "medium",
        "next_action": "Approve automation rules, add audit workflow and governance boundaries",
        "sort_order": 10,
        "accent": "purple",
        "views": ["cybersecurity_team"],
    },
]

VERIFICATION_BADGE_COLORS = {
    "Verified Executive": ("green", "check-circle"),
    "Verified Bio": ("green", "check-circle"),
    "Verified Function": ("green", "check-circle"),
    "In Review": ("yellow", "clock"),
    "Modified Profile": ("amber", "edit"),
    "Pending Approval": ("orange", "loader"),
    "Pending": ("orange", "loader"),
}

LICENSE_BADGE_COLORS = {
    "Approved": ("green", "badge-check"),
    "Review Active": ("blue", "refresh-cw"),
    "Not Required": ("slate", "minus-circle"),
    "Conditional": ("blue", "info"),
    "Evidence Required": ("red", "alert-triangle"),
    "Credential Evidence Required": ("orange", "alert-circle"),
    "Pending Review": ("amber", "clock"),
}

CEO_BADGE_COLORS = {
    "Approved": ("green", "badge-check"),
    "Pending": ("amber", "clock"),
    "Pending GEM + ATR Assignment Approval": ("amber", "clock"),
}

PLATFORM_PRODUCTS = [
    {"name": "GEM Security Operations Dashboard", "division": "GEM Cybersecurity", "status": "Active", "verification": "Approved", "owner": "Cyber Ops"},
    {"name": "Compliance Vault", "division": "GEM Cybersecurity", "status": "Active", "verification": "Approved", "owner": "Compliance"},
    {"name": "Vulnerability Scan Package", "division": "GEM Cybersecurity", "status": "Active", "verification": "Approved", "owner": "Cyber Ops"},
    {"name": "Financial Shield", "division": "GEM Financial Support", "status": "Review", "verification": "Evidence Required", "owner": "Financial Support"},
    {"name": "ATR Property Trust", "division": "ATR Realty", "status": "Review", "verification": "Evidence Required", "owner": "ATR"},
    {"name": "VIP Client Desk", "division": "GEM + ATR", "status": "Active", "verification": "Approved", "owner": "CEO Office"},
    {"name": "AI Agent Overseer", "division": "GEM Platform", "status": "Draft", "verification": "Pending Approval", "owner": "Platform Ops"},
    {"name": "License Evidence Registry", "division": "GEM + ATR", "status": "Active", "verification": "Approved", "owner": "CEO Office"},
]

def get_profiles_by_view(view_name):
    return sorted([p for p in GEM_PROFILES if view_name in p.get("views", [])], key=lambda x: x["sort_order"])

def get_all_profiles():
    return sorted(GEM_PROFILES, key=lambda x: x["sort_order"])
